name: build-packages

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.arch }}-${{ matrix.branch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - x86_64
        branch:
          - openwrt-23.05
          - openwrt-24.10
        exclude:
          - arch: aarch64_cortex-a76
            branch: openwrt-23.05
          - arch: mips_4kec
            branch: SNAPSHOT

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: nikki
          PACKAGES: luci-app-nikki
          NO_REFRESH_CHECK: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nikki_${{ matrix.arch }}-${{ matrix.branch }}
          path: bin/packages/${{ matrix.arch }}/nikki

      # === Kirim semua file .ipk ke Telegram ===
      - name: Send all .ipk files to Telegram
        if: success()
        run: |
          for f in $(find bin/packages/${{ matrix.arch }}/nikki -type f -name '*.ipk'); do
            curl -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
                 -F document=@$f \
                 -F caption="✅ Build: ${{ matrix.arch }} - ${{ matrix.branch }} ($(basename $f))" \
                 https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument
            sleep 2
          done
          
